# coding: utf-8

"""
    Experimental Looker API 3.1 Preview

    This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.   # noqa: E501

    OpenAPI spec version: 3.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import looker_client_31
from looker_client_31.api.content_api import ContentApi  # noqa: E501
from looker_client_31.rest import ApiException


class TestContentApi(unittest.TestCase):
    """ContentApi unit test stubs"""

    def setUp(self):
        self.api = looker_client_31.api.content_api.ContentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_all_content_metadata_accesses(self):
        """Test case for all_content_metadata_accesses

        Get All Content Metadata Accesses  # noqa: E501
        """
        pass

    def test_all_content_metadatas(self):
        """Test case for all_content_metadatas

        Get All Content Metadatas  # noqa: E501
        """
        pass

    def test_content_favorite(self):
        """Test case for content_favorite

        Get Favorite Content  # noqa: E501
        """
        pass

    def test_content_metadata(self):
        """Test case for content_metadata

        Get Content Metadata  # noqa: E501
        """
        pass

    def test_create_content_favorite(self):
        """Test case for create_content_favorite

        Create Favorite Content  # noqa: E501
        """
        pass

    def test_create_content_metadata_access(self):
        """Test case for create_content_metadata_access

        Create Content Metadata Access  # noqa: E501
        """
        pass

    def test_delete_content_favorite(self):
        """Test case for delete_content_favorite

        Delete Favorite Content  # noqa: E501
        """
        pass

    def test_delete_content_metadata_access(self):
        """Test case for delete_content_metadata_access

        Delete Content Metadata Access  # noqa: E501
        """
        pass

    def test_search_content_favorites(self):
        """Test case for search_content_favorites

        Search Favorite Contents  # noqa: E501
        """
        pass

    def test_search_content_views(self):
        """Test case for search_content_views

        Search Content Views  # noqa: E501
        """
        pass

    def test_update_content_metadata(self):
        """Test case for update_content_metadata

        Update Content Metadata  # noqa: E501
        """
        pass

    def test_update_content_metadata_access(self):
        """Test case for update_content_metadata_access

        Update Content Metadata Access  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
