# coding: utf-8

"""
    Experimental Looker API 3.1 Preview

    This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.   # noqa: E501

    OpenAPI spec version: 3.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import looker_client_31
from looker_client_31.api.config_api import ConfigApi  # noqa: E501
from looker_client_31.rest import ApiException


class TestConfigApi(unittest.TestCase):
    """ConfigApi unit test stubs"""

    def setUp(self):
        self.api = looker_client_31.api.config_api.ConfigApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_all_legacy_features(self):
        """Test case for all_legacy_features

        Get All Legacy Features  # noqa: E501
        """
        pass

    def test_all_timezones(self):
        """Test case for all_timezones

        Get All Timezones  # noqa: E501
        """
        pass

    def test_backup_configuration(self):
        """Test case for backup_configuration

        Get Backup Configuration  # noqa: E501
        """
        pass

    def test_legacy_feature(self):
        """Test case for legacy_feature

        Get Legacy Feature  # noqa: E501
        """
        pass

    def test_update_backup_configuration(self):
        """Test case for update_backup_configuration

        Update Backup Configuration  # noqa: E501
        """
        pass

    def test_update_legacy_feature(self):
        """Test case for update_legacy_feature

        Update Legacy Feature  # noqa: E501
        """
        pass

    def test_update_whitelabel_configuration(self):
        """Test case for update_whitelabel_configuration

        Update Whitelabel configuration  # noqa: E501
        """
        pass

    def test_versions(self):
        """Test case for versions

        Get ApiVersion  # noqa: E501
        """
        pass

    def test_whitelabel_configuration(self):
        """Test case for whitelabel_configuration

        Get Whitelabel configuration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
