# coding: utf-8

"""
    Experimental Looker API 3.1 Preview

    This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.   # noqa: E501

    OpenAPI spec version: 3.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import looker_client_31
from looker_client_31.api.query_api import QueryApi  # noqa: E501
from looker_client_31.rest import ApiException


class TestQueryApi(unittest.TestCase):
    """QueryApi unit test stubs"""

    def setUp(self):
        self.api = looker_client_31.api.query_api.QueryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_merge_query(self):
        """Test case for create_merge_query

        Create Merge Query  # noqa: E501
        """
        pass

    def test_create_query(self):
        """Test case for create_query

        Create Query  # noqa: E501
        """
        pass

    def test_create_query_task(self):
        """Test case for create_query_task

        Run Query Async  # noqa: E501
        """
        pass

    def test_merge_query(self):
        """Test case for merge_query

        Get Merge Query  # noqa: E501
        """
        pass

    def test_query(self):
        """Test case for query

        Get Query  # noqa: E501
        """
        pass

    def test_query_for_slug(self):
        """Test case for query_for_slug

        Get Query for Slug  # noqa: E501
        """
        pass

    def test_query_task(self):
        """Test case for query_task

        Get Async Query Info  # noqa: E501
        """
        pass

    def test_query_task_multi_results(self):
        """Test case for query_task_multi_results

        Get Multiple Async Query Results  # noqa: E501
        """
        pass

    def test_query_task_results(self):
        """Test case for query_task_results

        Get Async Query Results  # noqa: E501
        """
        pass

    def test_run_inline_query(self):
        """Test case for run_inline_query

        Run Inline Query  # noqa: E501
        """
        pass

    def test_run_query(self):
        """Test case for run_query

        Run Query  # noqa: E501
        """
        pass

    def test_run_url_encoded_query(self):
        """Test case for run_url_encoded_query

        Run Url Encoded Query  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
