# coding: utf-8

"""
    Experimental Looker API 3.1 Preview

    This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.   # noqa: E501

    OpenAPI spec version: 3.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import looker_client_31
from looker_client_31.api.dashboard_api import DashboardApi  # noqa: E501
from looker_client_31.rest import ApiException


class TestDashboardApi(unittest.TestCase):
    """DashboardApi unit test stubs"""

    def setUp(self):
        self.api = looker_client_31.api.dashboard_api.DashboardApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_all_dashboards(self):
        """Test case for all_dashboards

        Get All Dashboards  # noqa: E501
        """
        pass

    def test_create_dashboard(self):
        """Test case for create_dashboard

        Create Dashboard  # noqa: E501
        """
        pass

    def test_create_dashboard_element(self):
        """Test case for create_dashboard_element

        Create DashboardElement  # noqa: E501
        """
        pass

    def test_create_dashboard_filter(self):
        """Test case for create_dashboard_filter

        Create Dashboard Filter  # noqa: E501
        """
        pass

    def test_create_dashboard_layout(self):
        """Test case for create_dashboard_layout

        Create DashboardLayout  # noqa: E501
        """
        pass

    def test_dashboard(self):
        """Test case for dashboard

        Get Dashboard  # noqa: E501
        """
        pass

    def test_dashboard_dashboard_elements(self):
        """Test case for dashboard_dashboard_elements

        Get All DashboardElements  # noqa: E501
        """
        pass

    def test_dashboard_dashboard_filters(self):
        """Test case for dashboard_dashboard_filters

        Get All Dashboard Filters  # noqa: E501
        """
        pass

    def test_dashboard_dashboard_layouts(self):
        """Test case for dashboard_dashboard_layouts

        Get All DashboardLayouts  # noqa: E501
        """
        pass

    def test_dashboard_element(self):
        """Test case for dashboard_element

        Get DashboardElement  # noqa: E501
        """
        pass

    def test_dashboard_filter(self):
        """Test case for dashboard_filter

        Get Dashboard Filter  # noqa: E501
        """
        pass

    def test_dashboard_layout(self):
        """Test case for dashboard_layout

        Get DashboardLayout  # noqa: E501
        """
        pass

    def test_dashboard_layout_component(self):
        """Test case for dashboard_layout_component

        Get DashboardLayoutComponent  # noqa: E501
        """
        pass

    def test_dashboard_layout_dashboard_layout_components(self):
        """Test case for dashboard_layout_dashboard_layout_components

        Get All DashboardLayoutComponents  # noqa: E501
        """
        pass

    def test_delete_dashboard(self):
        """Test case for delete_dashboard

        Delete Dashboard  # noqa: E501
        """
        pass

    def test_delete_dashboard_element(self):
        """Test case for delete_dashboard_element

        Delete DashboardElement  # noqa: E501
        """
        pass

    def test_delete_dashboard_filter(self):
        """Test case for delete_dashboard_filter

        Delete Dashboard Filter  # noqa: E501
        """
        pass

    def test_delete_dashboard_layout(self):
        """Test case for delete_dashboard_layout

        Delete DashboardLayout  # noqa: E501
        """
        pass

    def test_search_dashboard_elements(self):
        """Test case for search_dashboard_elements

        Get DashboardElement  # noqa: E501
        """
        pass

    def test_search_dashboards(self):
        """Test case for search_dashboards

        Search Dashboards  # noqa: E501
        """
        pass

    def test_update_dashboard(self):
        """Test case for update_dashboard

        Update Dashboard  # noqa: E501
        """
        pass

    def test_update_dashboard_element(self):
        """Test case for update_dashboard_element

        Update DashboardElement  # noqa: E501
        """
        pass

    def test_update_dashboard_filter(self):
        """Test case for update_dashboard_filter

        Update Dashboard Filter  # noqa: E501
        """
        pass

    def test_update_dashboard_layout(self):
        """Test case for update_dashboard_layout

        Update DashboardLayout  # noqa: E501
        """
        pass

    def test_update_dashboard_layout_component(self):
        """Test case for update_dashboard_layout_component

        Update DashboardLayoutComponent  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
