# coding: utf-8

"""
    Experimental Looker API 3.1 Preview

    This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.   # noqa: E501

    OpenAPI spec version: 3.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import looker_client_31
from looker_client_31.looker_sdk.lookml_model_explore_supported_measure_type import LookmlModelExploreSupportedMeasureType  # noqa: E501
from looker_client_31.rest import ApiException


class TestLookmlModelExploreSupportedMeasureType(unittest.TestCase):
    """LookmlModelExploreSupportedMeasureType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLookmlModelExploreSupportedMeasureType(self):
        """Test LookmlModelExploreSupportedMeasureType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = looker_client_31.models.lookml_model_explore_supported_measure_type.LookmlModelExploreSupportedMeasureType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
