# coding: utf-8

"""
    Experimental Looker API 3.1 Preview

    This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.   # noqa: E501

    OpenAPI spec version: 3.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import looker_client_31
from looker_client_31.api.connection_api import ConnectionApi  # noqa: E501
from looker_client_31.rest import ApiException


class TestConnectionApi(unittest.TestCase):
    """ConnectionApi unit test stubs"""

    def setUp(self):
        self.api = looker_client_31.api.connection_api.ConnectionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_all_connections(self):
        """Test case for all_connections

        Get All Connections  # noqa: E501
        """
        pass

    def test_all_dialect_infos(self):
        """Test case for all_dialect_infos

        Get All Dialect Infos  # noqa: E501
        """
        pass

    def test_connection(self):
        """Test case for connection

        Get Connection  # noqa: E501
        """
        pass

    def test_create_connection(self):
        """Test case for create_connection

        Create Connection  # noqa: E501
        """
        pass

    def test_delete_connection(self):
        """Test case for delete_connection

        Delete Connection  # noqa: E501
        """
        pass

    def test_delete_connection_override(self):
        """Test case for delete_connection_override

        Delete Connection  # noqa: E501
        """
        pass

    def test_test_connection(self):
        """Test case for test_connection

        Test Connection  # noqa: E501
        """
        pass

    def test_test_connection_config(self):
        """Test case for test_connection_config

        Test Connection Configuration  # noqa: E501
        """
        pass

    def test_update_connection(self):
        """Test case for update_connection

        Update Connection  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
