# coding: utf-8

"""
    Experimental Looker API 3.1 Preview

    This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.   # noqa: E501

    OpenAPI spec version: 3.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import looker_client_31
from looker_client_31.api.look_api import LookApi  # noqa: E501
from looker_client_31.rest import ApiException


class TestLookApi(unittest.TestCase):
    """LookApi unit test stubs"""

    def setUp(self):
        self.api = looker_client_31.api.look_api.LookApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_all_looks(self):
        """Test case for all_looks

        Get All Looks  # noqa: E501
        """
        pass

    def test_create_look(self):
        """Test case for create_look

        Create Look  # noqa: E501
        """
        pass

    def test_delete_look(self):
        """Test case for delete_look

        Delete Look  # noqa: E501
        """
        pass

    def test_look(self):
        """Test case for look

        Get Look  # noqa: E501
        """
        pass

    def test_run_look(self):
        """Test case for run_look

        Run Look  # noqa: E501
        """
        pass

    def test_search_looks(self):
        """Test case for search_looks

        Search Looks  # noqa: E501
        """
        pass

    def test_update_look(self):
        """Test case for update_look

        Update Look  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
