# coding: utf-8

"""
    Experimental Looker API 3.1 Preview

    This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.   # noqa: E501

    OpenAPI spec version: 3.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import looker_client_31
from looker_client_31.api.integration_api import IntegrationApi  # noqa: E501
from looker_client_31.rest import ApiException


class TestIntegrationApi(unittest.TestCase):
    """IntegrationApi unit test stubs"""

    def setUp(self):
        self.api = looker_client_31.api.integration_api.IntegrationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accept_integration_hub_legal_agreement(self):
        """Test case for accept_integration_hub_legal_agreement

        Accept Integration Hub Legal Agreement  # noqa: E501
        """
        pass

    def test_all_integration_hubs(self):
        """Test case for all_integration_hubs

        Get All Integration Hubs  # noqa: E501
        """
        pass

    def test_all_integrations(self):
        """Test case for all_integrations

        Get All Integrations  # noqa: E501
        """
        pass

    def test_create_integration_hub(self):
        """Test case for create_integration_hub

        Create Integration Hub  # noqa: E501
        """
        pass

    def test_delete_integration_hub(self):
        """Test case for delete_integration_hub

        Delete Integration Hub  # noqa: E501
        """
        pass

    def test_fetch_integration_form(self):
        """Test case for fetch_integration_form

        Fetch Remote Integration Form  # noqa: E501
        """
        pass

    def test_integration(self):
        """Test case for integration

        Get Integration  # noqa: E501
        """
        pass

    def test_integration_hub(self):
        """Test case for integration_hub

        Get Integration Hub  # noqa: E501
        """
        pass

    def test_update_integration(self):
        """Test case for update_integration

        Update Integration  # noqa: E501
        """
        pass

    def test_update_integration_hub(self):
        """Test case for update_integration_hub

        Update Integration Hub  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
