# coding: utf-8

"""
    Experimental Looker API 3.1 Preview

    This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.   # noqa: E501

    OpenAPI spec version: 3.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import looker_client_31
from looker_client_31.api.auth_api import AuthApi  # noqa: E501
from looker_client_31.rest import ApiException


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self):
        self.api = looker_client_31.api.auth_api.AuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_oidc_test_config(self):
        """Test case for create_oidc_test_config

        Create OIDC Test Configuration  # noqa: E501
        """
        pass

    def test_create_saml_test_config(self):
        """Test case for create_saml_test_config

        Create SAML Test Configuration  # noqa: E501
        """
        pass

    def test_delete_oidc_test_config(self):
        """Test case for delete_oidc_test_config

        Delete OIDC Test Configuration  # noqa: E501
        """
        pass

    def test_delete_saml_test_config(self):
        """Test case for delete_saml_test_config

        Delete SAML Test Configuration  # noqa: E501
        """
        pass

    def test_fetch_and_parse_saml_idp_metadata(self):
        """Test case for fetch_and_parse_saml_idp_metadata

        Parse SAML IdP Url  # noqa: E501
        """
        pass

    def test_ldap_config(self):
        """Test case for ldap_config

        Get LDAP Configuration  # noqa: E501
        """
        pass

    def test_oidc_config(self):
        """Test case for oidc_config

        Get OIDC Configuration  # noqa: E501
        """
        pass

    def test_oidc_test_config(self):
        """Test case for oidc_test_config

        Get OIDC Test Configuration  # noqa: E501
        """
        pass

    def test_parse_saml_idp_metadata(self):
        """Test case for parse_saml_idp_metadata

        Parse SAML IdP XML  # noqa: E501
        """
        pass

    def test_saml_config(self):
        """Test case for saml_config

        Get SAML Configuration  # noqa: E501
        """
        pass

    def test_saml_test_config(self):
        """Test case for saml_test_config

        Get SAML Test Configuration  # noqa: E501
        """
        pass

    def test_test_ldap_config_auth(self):
        """Test case for test_ldap_config_auth

        Test LDAP Auth  # noqa: E501
        """
        pass

    def test_test_ldap_config_connection(self):
        """Test case for test_ldap_config_connection

        Test LDAP Connection  # noqa: E501
        """
        pass

    def test_test_ldap_config_user_auth(self):
        """Test case for test_ldap_config_user_auth

        Test LDAP User Auth  # noqa: E501
        """
        pass

    def test_test_ldap_config_user_info(self):
        """Test case for test_ldap_config_user_info

        Test LDAP User Info  # noqa: E501
        """
        pass

    def test_update_ldap_config(self):
        """Test case for update_ldap_config

        Update LDAP Configuration  # noqa: E501
        """
        pass

    def test_update_oidc_config(self):
        """Test case for update_oidc_config

        Update OIDC Configuration  # noqa: E501
        """
        pass

    def test_update_saml_config(self):
        """Test case for update_saml_config

        Update SAML Configuration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
