# coding: utf-8

"""
    Experimental Looker API 3.1 Preview

    This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.   # noqa: E501

    OpenAPI spec version: 3.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import looker_client_31
from looker_client_31.api.group_api import GroupApi  # noqa: E501
from looker_client_31.rest import ApiException


class TestGroupApi(unittest.TestCase):
    """GroupApi unit test stubs"""

    def setUp(self):
        self.api = looker_client_31.api.group_api.GroupApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_group_group(self):
        """Test case for add_group_group

        Add a Group to Group  # noqa: E501
        """
        pass

    def test_add_group_user(self):
        """Test case for add_group_user

        Add a User to Group  # noqa: E501
        """
        pass

    def test_all_group_groups(self):
        """Test case for all_group_groups

        Get All Groups in Group  # noqa: E501
        """
        pass

    def test_all_group_users(self):
        """Test case for all_group_users

        Get All Users in Group  # noqa: E501
        """
        pass

    def test_all_groups(self):
        """Test case for all_groups

        Get All Groups  # noqa: E501
        """
        pass

    def test_create_group(self):
        """Test case for create_group

        Create Group  # noqa: E501
        """
        pass

    def test_delete_group(self):
        """Test case for delete_group

        Delete Group  # noqa: E501
        """
        pass

    def test_delete_group_from_group(self):
        """Test case for delete_group_from_group

        Deletes a Group from Group  # noqa: E501
        """
        pass

    def test_delete_group_user(self):
        """Test case for delete_group_user

        Remove a User from Group  # noqa: E501
        """
        pass

    def test_delete_user_attribute_group_value(self):
        """Test case for delete_user_attribute_group_value

        Delete User Attribute Group Value  # noqa: E501
        """
        pass

    def test_group(self):
        """Test case for group

        Get Group  # noqa: E501
        """
        pass

    def test_update_group(self):
        """Test case for update_group

        Update Group  # noqa: E501
        """
        pass

    def test_update_user_attribute_group_value(self):
        """Test case for update_user_attribute_group_value

        Set User Attribute Group Value  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
