# coding: utf-8

"""
    Experimental Looker API 3.1 Preview

    This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.   # noqa: E501

    OpenAPI spec version: 3.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import looker_client_31
from looker_client_31.api.user_api import UserApi  # noqa: E501
from looker_client_31.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = looker_client_31.api.user_api.UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_all_user_access_filters(self):
        """Test case for all_user_access_filters

        Get All Access Filters  # noqa: E501
        """
        pass

    def test_all_user_credentials_api3s(self):
        """Test case for all_user_credentials_api3s

        Get All API 3 Credentials  # noqa: E501
        """
        pass

    def test_all_user_credentials_embeds(self):
        """Test case for all_user_credentials_embeds

        Get All Embedding Credentials  # noqa: E501
        """
        pass

    def test_all_user_sessions(self):
        """Test case for all_user_sessions

        Get All Web Login Sessions  # noqa: E501
        """
        pass

    def test_all_users(self):
        """Test case for all_users

        Get All Users  # noqa: E501
        """
        pass

    def test_create_user(self):
        """Test case for create_user

        Create User  # noqa: E501
        """
        pass

    def test_create_user_access_filter(self):
        """Test case for create_user_access_filter

        Create Access Filter  # noqa: E501
        """
        pass

    def test_create_user_credentials_api(self):
        """Test case for create_user_credentials_api

        Create API Credential  # noqa: E501
        """
        pass

    def test_create_user_credentials_api3(self):
        """Test case for create_user_credentials_api3

        Create API 3 Credential  # noqa: E501
        """
        pass

    def test_create_user_credentials_email(self):
        """Test case for create_user_credentials_email

        Create Email/Password Credential  # noqa: E501
        """
        pass

    def test_create_user_credentials_email_password_reset(self):
        """Test case for create_user_credentials_email_password_reset

        Create Password Reset Token  # noqa: E501
        """
        pass

    def test_create_user_credentials_totp(self):
        """Test case for create_user_credentials_totp

        Create Two-Factor Credential  # noqa: E501
        """
        pass

    def test_delete_user(self):
        """Test case for delete_user

        Delete User  # noqa: E501
        """
        pass

    def test_delete_user_access_filter(self):
        """Test case for delete_user_access_filter

        Delete Access Filter  # noqa: E501
        """
        pass

    def test_delete_user_attribute_user_value(self):
        """Test case for delete_user_attribute_user_value

        Delete User Attribute User Value  # noqa: E501
        """
        pass

    def test_delete_user_credentials_api(self):
        """Test case for delete_user_credentials_api

        Delete API Credential  # noqa: E501
        """
        pass

    def test_delete_user_credentials_api3(self):
        """Test case for delete_user_credentials_api3

        Delete API 3 Credential  # noqa: E501
        """
        pass

    def test_delete_user_credentials_email(self):
        """Test case for delete_user_credentials_email

        Delete Email/Password Credential  # noqa: E501
        """
        pass

    def test_delete_user_credentials_embed(self):
        """Test case for delete_user_credentials_embed

        Delete Embedding Credential  # noqa: E501
        """
        pass

    def test_delete_user_credentials_google(self):
        """Test case for delete_user_credentials_google

        Delete Google Auth Credential  # noqa: E501
        """
        pass

    def test_delete_user_credentials_ldap(self):
        """Test case for delete_user_credentials_ldap

        Delete LDAP Credential  # noqa: E501
        """
        pass

    def test_delete_user_credentials_looker_openid(self):
        """Test case for delete_user_credentials_looker_openid

        Delete Looker OpenId Credential  # noqa: E501
        """
        pass

    def test_delete_user_credentials_oidc(self):
        """Test case for delete_user_credentials_oidc

        Delete OIDC Auth Credential  # noqa: E501
        """
        pass

    def test_delete_user_credentials_saml(self):
        """Test case for delete_user_credentials_saml

        Delete Saml Auth Credential  # noqa: E501
        """
        pass

    def test_delete_user_credentials_totp(self):
        """Test case for delete_user_credentials_totp

        Delete Two-Factor Credential  # noqa: E501
        """
        pass

    def test_delete_user_session(self):
        """Test case for delete_user_session

        Delete Web Login Session  # noqa: E501
        """
        pass

    def test_me(self):
        """Test case for me

        Get Current User  # noqa: E501
        """
        pass

    def test_search_users(self):
        """Test case for search_users

        Search Users  # noqa: E501
        """
        pass

    def test_search_users_names(self):
        """Test case for search_users_names

        Search User Names  # noqa: E501
        """
        pass

    def test_set_user_attribute_user_value(self):
        """Test case for set_user_attribute_user_value

        Set User Attribute User Value  # noqa: E501
        """
        pass

    def test_set_user_roles(self):
        """Test case for set_user_roles

        Set User Roles  # noqa: E501
        """
        pass

    def test_update_user(self):
        """Test case for update_user

        Update User  # noqa: E501
        """
        pass

    def test_update_user_access_filter(self):
        """Test case for update_user_access_filter

        Update Access Filter  # noqa: E501
        """
        pass

    def test_update_user_credentials_email(self):
        """Test case for update_user_credentials_email

        Update Email/Password Credential  # noqa: E501
        """
        pass

    def test_user(self):
        """Test case for user

        Get User by Id  # noqa: E501
        """
        pass

    def test_user_access_filter(self):
        """Test case for user_access_filter

        Get Access Filter  # noqa: E501
        """
        pass

    def test_user_attribute_user_values(self):
        """Test case for user_attribute_user_values

        Get User Attribute Values  # noqa: E501
        """
        pass

    def test_user_credentials_api(self):
        """Test case for user_credentials_api

        Get API Credential  # noqa: E501
        """
        pass

    def test_user_credentials_api3(self):
        """Test case for user_credentials_api3

        Get API 3 Credential  # noqa: E501
        """
        pass

    def test_user_credentials_email(self):
        """Test case for user_credentials_email

        Get Email/Password Credential  # noqa: E501
        """
        pass

    def test_user_credentials_embed(self):
        """Test case for user_credentials_embed

        Get Embedding Credential  # noqa: E501
        """
        pass

    def test_user_credentials_google(self):
        """Test case for user_credentials_google

        Get Google Auth Credential  # noqa: E501
        """
        pass

    def test_user_credentials_ldap(self):
        """Test case for user_credentials_ldap

        Get LDAP Credential  # noqa: E501
        """
        pass

    def test_user_credentials_looker_openid(self):
        """Test case for user_credentials_looker_openid

        Get Looker OpenId Credential  # noqa: E501
        """
        pass

    def test_user_credentials_oidc(self):
        """Test case for user_credentials_oidc

        Get OIDC Auth Credential  # noqa: E501
        """
        pass

    def test_user_credentials_saml(self):
        """Test case for user_credentials_saml

        Get Saml Auth Credential  # noqa: E501
        """
        pass

    def test_user_credentials_totp(self):
        """Test case for user_credentials_totp

        Get Two-Factor Credential  # noqa: E501
        """
        pass

    def test_user_for_credential(self):
        """Test case for user_for_credential

        Get User by Credential Id  # noqa: E501
        """
        pass

    def test_user_roles(self):
        """Test case for user_roles

        Get User Roles  # noqa: E501
        """
        pass

    def test_user_session(self):
        """Test case for user_session

        Get Web Login Session  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
