# coding: utf-8

"""
    Experimental Looker API 3.1 Preview

    This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.   # noqa: E501

    OpenAPI spec version: 3.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import looker_client_31
from looker_client_31.api.lookml_model_api import LookmlModelApi  # noqa: E501
from looker_client_31.rest import ApiException


class TestLookmlModelApi(unittest.TestCase):
    """LookmlModelApi unit test stubs"""

    def setUp(self):
        self.api = looker_client_31.api.lookml_model_api.LookmlModelApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_all_lookml_models(self):
        """Test case for all_lookml_models

        Get All LookML Models  # noqa: E501
        """
        pass

    def test_create_lookml_model(self):
        """Test case for create_lookml_model

        Create LookML Model  # noqa: E501
        """
        pass

    def test_delete_lookml_model(self):
        """Test case for delete_lookml_model

        Delete LookML Model  # noqa: E501
        """
        pass

    def test_lookml_model(self):
        """Test case for lookml_model

        Get LookML Model  # noqa: E501
        """
        pass

    def test_lookml_model_explore(self):
        """Test case for lookml_model_explore

        Get LookML Model Explore  # noqa: E501
        """
        pass

    def test_update_lookml_model(self):
        """Test case for update_lookml_model

        Update LookML Model  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
