# coding: utf-8

"""
    Experimental Looker API 3.1 Preview

    This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.   # noqa: E501

    OpenAPI spec version: 3.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import looker_client_31
from looker_client_31.api.project_api import ProjectApi  # noqa: E501
from looker_client_31.rest import ApiException


class TestProjectApi(unittest.TestCase):
    """ProjectApi unit test stubs"""

    def setUp(self):
        self.api = looker_client_31.api.project_api.ProjectApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_all_git_branches(self):
        """Test case for all_git_branches

        Get All Git Branchs  # noqa: E501
        """
        pass

    def test_all_git_connection_tests(self):
        """Test case for all_git_connection_tests

        Get All Git Connection Tests  # noqa: E501
        """
        pass

    def test_all_project_files(self):
        """Test case for all_project_files

        Get All Project Files  # noqa: E501
        """
        pass

    def test_all_projects(self):
        """Test case for all_projects

        Get All Projects  # noqa: E501
        """
        pass

    def test_create_git_deploy_key(self):
        """Test case for create_git_deploy_key

        Create Deploy Key  # noqa: E501
        """
        pass

    def test_create_project(self):
        """Test case for create_project

        Create Project  # noqa: E501
        """
        pass

    def test_git_deploy_key(self):
        """Test case for git_deploy_key

        Git Deploy Key  # noqa: E501
        """
        pass

    def test_project(self):
        """Test case for project

        Get Project  # noqa: E501
        """
        pass

    def test_project_file(self):
        """Test case for project_file

        Get Project File  # noqa: E501
        """
        pass

    def test_project_validation_results(self):
        """Test case for project_validation_results

        Cached Project Validation Results  # noqa: E501
        """
        pass

    def test_project_workspace(self):
        """Test case for project_workspace

        Get Project Workspace  # noqa: E501
        """
        pass

    def test_reset_project_to_production(self):
        """Test case for reset_project_to_production

        Reset To Production  # noqa: E501
        """
        pass

    def test_reset_project_to_remote(self):
        """Test case for reset_project_to_remote

        Reset To Remote  # noqa: E501
        """
        pass

    def test_run_git_connection_test(self):
        """Test case for run_git_connection_test

        Run Git Connection Test  # noqa: E501
        """
        pass

    def test_update_project(self):
        """Test case for update_project

        Update Project  # noqa: E501
        """
        pass

    def test_validate_project(self):
        """Test case for validate_project

        Validate Project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
