# coding: utf-8

"""
    Experimental Looker API 3.1 Preview

    This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.   # noqa: E501

    OpenAPI spec version: 3.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Permission(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'permission': 'str',
        'parent': 'str',
        'description': 'str',
        'can': 'dict(str, bool)'
    }

    attribute_map = {
        'permission': 'permission',
        'parent': 'parent',
        'description': 'description',
        'can': 'can'
    }

    def __init__(self, permission=None, parent=None, description=None, can=None):  # noqa: E501
        """Permission - a model defined in Swagger"""  # noqa: E501

        self._permission = None
        self._parent = None
        self._description = None
        self._can = None
        self.discriminator = None

        if permission is not None:
            self.permission = permission
        if parent is not None:
            self.parent = parent
        if description is not None:
            self.description = description
        if can is not None:
            self.can = can

    @property
    def permission(self):
        """Gets the permission of this Permission.  # noqa: E501

        Permission symbol  # noqa: E501

        :return: The permission of this Permission.  # noqa: E501
        :rtype: str
        """
        return self._permission

    @permission.setter
    def permission(self, permission):
        """Sets the permission of this Permission.

        Permission symbol  # noqa: E501

        :param permission: The permission of this Permission.  # noqa: E501
        :type: str
        """

        self._permission = permission

    @property
    def parent(self):
        """Gets the parent of this Permission.  # noqa: E501

        Dependency parent symbol  # noqa: E501

        :return: The parent of this Permission.  # noqa: E501
        :rtype: str
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """Sets the parent of this Permission.

        Dependency parent symbol  # noqa: E501

        :param parent: The parent of this Permission.  # noqa: E501
        :type: str
        """

        self._parent = parent

    @property
    def description(self):
        """Gets the description of this Permission.  # noqa: E501

        Description  # noqa: E501

        :return: The description of this Permission.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Permission.

        Description  # noqa: E501

        :param description: The description of this Permission.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def can(self):
        """Gets the can of this Permission.  # noqa: E501

        Operations the current user is able to perform on this object  # noqa: E501

        :return: The can of this Permission.  # noqa: E501
        :rtype: dict(str, bool)
        """
        return self._can

    @can.setter
    def can(self, can):
        """Sets the can of this Permission.

        Operations the current user is able to perform on this object  # noqa: E501

        :param can: The can of this Permission.  # noqa: E501
        :type: dict(str, bool)
        """

        self._can = can

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Permission):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
